name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{secrets.AWS_REGION}} # Replace with your EKS cluster's region

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ${{secrets.AWS_REGION}} --name my-eks-cluster

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push frontend Docker image
      run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest -f Frontend/Dockerfile ./Frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: Build and push backend Docker image
      run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest -f Backend/Dockerfile ./Backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

    - name: Deploy to EKS
      run: |
        kubectl apply -f foodtube/frontendapp/deploy.yaml
        kubectl apply -f foodtube/backendapp/deploy.yaml